### ISSUE TITLE
Hanging forever 

### ISSUE THREAD

**Issue by nilotpalsrkr** [apangin/jattach#23] opened 2019-05-21 13:48 UTC
# ./jattach 2233 properties
Connected to remote JVM
Response code =

**Comment by apangin** [comment] 2019-09-22 22:49
Closing the issue as there is no response from the submitter.
The described behavior seems like a problem with the JVM and is not a bug of jattach.

**Comment by heatzync** [comment] 2022-05-27 10:42
I experienced this same problem when trying to attach to a JVM process that was started by a different user.

For example, I was running `jattach` in a PowerShell that was started as an Administrator trying to attach to a JVM process that was started by a normal user.

Running `jattach` in a _normal_ PowerShell (not started as Administrator) I was able to attach to a JVM process that was also started by the same user.

**Comment by apangin** [comment] 2022-05-27 13:54
The problem is understood; will prepare a fix.

**Comment by apangin** [comment] 2022-07-24 23:52
Fixed in 2.1

**Closed by apangin** 2022-07-24 23:52 UTC
