### ISSUE TITLE
Error "Not a HPROF heap dump"

### ISSUE THREAD

**Issue by amao12580** [apangin/jattach#20] opened 2019-05-08 06:18 UTC
when i try to dump heap for a living jvm,used follow command.

jattach 13174 dumpheap mydump.hprof

I'm used to using MemoryAnalyzer(mat,latest version) to analyze the dump heap.

but actually,the mat cannot open mydump.hprof,just reported a error:

_Error opening heap dump 'mydump.hprof'. Check the error log for further details.
Error opening heap dump 'mydump.hprof'. Check the error log for further details.
Not a HPROF heap dump (java.io.IOException)
Not a HPROF heap dump_

sorry for my pool English,please help and fix this bug.thanks.

**Comment by amao12580** [comment] 2019-05-09 01:52
1.Java version:
_openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)_

2.OS Version:Centos 7.4 X64 run on a vmware esxi server.

3.Yes,this problem happened by every living jvm.

4.The file **mydump.hprof** size  almost 260MB，not sure close to real heap size.

5.The **jattach** command has been success executed and print **Heap dump file created**

**Comment by amao12580** [comment] 2019-05-09 01:55
[root@172 ~]# jattach 70171 dumpheap mydump.hprof
Connected to remote JVM
Response code = 0
Heap dump file created

**Comment by apangin** [comment] 2019-05-09 17:23
Could not reproduce the problem. It's unlikely that the problem is in jattach.
Does a heap dump produced by `jmap` work fine?

If you could create a simple dump for a hello-world like application and send me a link to it, I would check what's wrong with it.

**Comment by apangin** [comment] 2019-09-22 22:47
Closing the issue, since it is not a bug of jattach, and there is no further feedback from the submitter.

**Closed by apangin** 2019-09-22 22:47 UTC
