### ISSUE TITLE
Attaching Response code = -1

### ISSUE THREAD

**Issue by bolunli11** [apangin/jattach#30] opened 2020-05-21 19:46 UTC
Hello,

I use below command to attach a JVMTI agent to a running JVM process:
./jattach 29341 load libagent.so true DataCentric::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@10000

There's an Agent-OnAttach method inside the libagent.so, and the jvm was started with -XX:+StartAttachListener. But I always got:
Connected to remote JVM
Response code = -1

Any help is appreciated!

**Comment by apangin** [comment] 2020-05-22 15:24
As discussed in #29, "Response code = -1" means that the problem is in the agent library, not in jattach.

1. Specify the full path to `/path/libagent.so` in the command line
2. Make sure `libagent.so` exports `Agent_OnAttach` function:  
`nm -D libagent.so | grep "T Agent_OnLoad"`
3. Verify that `libagent.so` does not have unresolved dependencies: `ldd libagent.so`
4. Make sure `Agent_OnAttach` returns 0

**Comment by bolunli11** [comment] 2020-05-23 19:38
Thanks. I added the function "Agent_OnAttach" in libagent.so, and I can find it by using "nm -D libagent.so | grep "T Agent_OnAttach". But when I run it with jattach, it showed "Agent_OnAttach is not available in libagent.so". Any thoughts here?

**Comment by apangin** [comment] 2020-05-23 20:13
Can you check if a simple "Hello World" agent works?
```
#include <stdio.h>

int Agent_OnAttach(void* vm, char* options, void* reserved) {
    printf("Agent loaded\n");
    return 0;
}
```

**Comment by bolunli11** [comment] 2020-05-23 20:43
Seems that the Agent_OnAttach is invoked, because I got a new error:

Connected to remote JVM
Response code = Error reading response: Success

The command I used is:
./jattach 111551 load /home/bli11/profiler/build/libagent.so true "NUMA::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@100000" 

The agent argument ("NUMA::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@100000") I used here is supposed to pass to the second input parameter (char* options) of Agent_OnAttach.

**Comment by bolunli11** [comment] 2020-05-23 21:15
I also tried your simpler "Hello World" agent without considering the argument thing, I still got the same error:

Connected to remote JVM
Response code = Error reading response: Success

And the running Java process crashed:
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000b2a6, pid=115690, tid=0x00007fd8495d5700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x000000000000b2a6
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/bli11/test/hs_err_pid115690.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)

Open the error log file, it showed the current thread is JavaThread "Attach Listener":
---------------  T H R E A D  ---------------
 Current thread (0x00007fd8ec001000):  JavaThread "Attach Listener" daemon [_thread_in_native, id=115883, stack(     0x00007fd8494d5000,0x00007fd8495d6000)]

 siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000000000b2a6

**Comment by apangin** [comment] 2020-05-23 22:41
Seems like you either compile the the library the wrong way, or overwrite the already loaded library.

Note that once the library named `libagent.so` has been loaded into the JVM, you won't be able to load a different library with the same name.

Can you please send me your compiled "HelloWorld" agent, so that I check if it is correct.

**Comment by bolunli11** [comment] 2020-05-24 00:34
Thanks! I loaded that agent twice so I got the "Error reading response".  I'm able to load the agent once, and it works. 

One more thing is that, how to detach? Actually my agent is also a profiler, I need to invoke the "callbacks.ThreadEnd" to collect the profiling result. Currently, it seems that every thread is running all the time and no thread notifies JVM that it is going to end.

**Comment by bolunli11** [comment] 2020-05-24 01:25
Another question is that, if I need to run a profiler with a Java agent and a JVMTI agent simultaneously, for example:

java -javaagent:agent1.jar -agentpath:agent2.so ...

Does jattach support to load these two agents together? Because these two agents have some communications between each other and I need them both at the same time, so I can't invoke a command twice with different arguments to load different agents.

**Comment by apangin** [comment] 2020-05-24 01:56
> how to detach?

HotSpot JVM does not support agent unloading. However, you may "attach" the same library multiple times with different arguments. The library will not be loaded again, but `Agent_OnAttach` will still be called multiple times with different arguments.

**Comment by apangin** [comment] 2020-05-24 02:05
> Does jattach support to load these two agents together?

Yes, it does. Just invoke jattach command twice.

Hint: when you run `java -javaagent:agent1.jar -agentpath:agent2.so ...` the agents are not loaded "together". They are loaded sequentially, one after another. After that, both agents coexist in the same JVM process. Loading two agents in runtime works exactly the same way.

**Comment by apangin** [comment] 2020-05-24 02:06
Closing the issue, as the original issue is resolved.

**Comment by apangin** [comment] 2020-05-24 02:07
Closing the issue, as the original question is resolved.

**Closed by apangin** 2020-05-24 02:06 UTC

**Comment by bolunli11** [comment] 2020-05-24 02:15
Thanks a lot. May I know how the async-profiler handles the situation that perf samples happen in malloc/free function? Taking samples inside a malloc/free function could result in a deadlock, right?

**Comment by apangin** [comment] 2020-05-24 09:08
In order to avoid deadlocks, an agent must not use unsafe functions (including malloc/free) inside the signal handler. There is a list of [async signal safe](http://man7.org/linux/man-pages/man7/signal-safety.7.html) functions that *can* be called.
