### ISSUE TITLE
Could not start attach in k8s ephemeral container: couldn't enter target process mnt namespace

### ISSUE THREAD

**Issue by hengyunabc** [apangin/jattach#44] opened 2021-07-28 07:25 UTC
* https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container

### start k8s

```
minikube start --feature-gates=EphemeralContainers=true
```

### start a simple java pod:

```
kubectl run arthas-demo --image=hengyunabc/atest:0.0.3
```

Dockerfile:

```
FROM openjdk:8-jdk
RUN wget https://arthas.aliyun.com/math-game.jar

ENTRYPOINT ["/bin/sh", "-c", "java -jar math-game.jar"]
```

Check pods status:

```
$ kubectl get pods
NAME          READY   STATUS    RESTARTS   AGE
arthas-demo   1/1     Running   0          5m58s
```

### Debug ephemeral containers

```
kubectl debug -it arthas-demo --image=openjdk:8-jdk --target=arthas-demo
```

```
root@arthas-demo:/# wget https://github.com/apangin/jattach/releases/download/v1.5/jattach
root@arthas-demo:/# chmod +x ./jattach
root@arthas-demo:/# ./jattach 9 agentProperties
WARNING: couldn't enter target process mnt namespace
Could not start attach mechanism: No such file or directory
```

**Comment by apangin** [comment] 2021-08-02 18:43
The problem is understood. I'll try to fix it later this week.

**Comment by apangin** [comment] 2021-08-11 00:25
The problem is fixed in [Release 2.0](https://github.com/apangin/jattach/releases/tag/v2.0).
Let me know if it works for you.

**Comment by hengyunabc** [comment] 2021-08-11 08:01
It works now, thanks.

Note: need to copy the jar file to the `/proc/$pid/root/` directory, for example:

```
cp test-agent.jar /proc/7/root/test-agent.jar
./jattach 7 load instrument false "/test-agent.jar"
```

**Comment by apangin** [comment] 2021-08-11 08:34
Thanks for confirming.

Right, jattach only invokes a command on the target process. `.jar` is loaded by the JVM itself, and the JVM can access only the container file system.

**Closed by apangin** 2021-08-11 08:34 UTC
Labels: bug
